### ISSUE TITLE
Windows Source Code

### ISSUE THREAD

**Issue by ArashPix** [gkngkc/UnityStandaloneFileBrowser#10]
Hi, Good job. I just couldn't find the windows version of plugin source code (Any Visual Studio project?)

**Comment by gkngkc** [comment]
Thanks,

Windows side uses Ookii.Dialogs lib, you can check it out [here](http://www.ookii.org/Software/Dialogs/)

**Comment by ArashPix** [comment]
Thanks, but I was wondering if the source code (c++) is accessible!!!

**Comment by gkngkc** [comment]
Ookii.Dialogs source code is available at their project page([download link](http://www.ookii.org/Download/Dialogs)). You can create your own dll's with it, but it's not C++, its C# (.NET).
