### ISSUE TITLE
Unity 2021.2.x and greater exception: "ArgumentException: Value must be a Com object."

### ISSUE THREAD

**Issue by music4computers** [gkngkc/UnityStandaloneFileBrowser#112]
In Unity 2021.2 and greater the Windows explorer window will come up and you're able to select a file, but then you immediately get an "**ArgumentException: Value must be a Com object.**" exception upon confirming the selection. Any guidance on what this exception means would be appreciated, thanks.

**Comment by bodhid** [comment]
@music4computers in case this project is not being worked on.

You can put a try/catch around "result = fd.ShowDialog(new WindowWrapper(GetActiveWindow()));" and check the contents of fd.filenames. 
The dialog will still popup and the paths can be retrieved

**Comment by music4computers** [comment]
I ended up just launching a file browser through a background process, but hopefully your solution will help other people running into this issue.  Thanks for the help.

**Comment by music4computers** [comment]
The Unity issue tracker claims this has been fixed: 
https://issuetracker.unity3d.com/issues/argumentexception-value-must-be-a-com-object-when-calling-system-dot-runtime-dot-interopservices-dot-marshal-dot-finalreleasecomobject
