### ISSUE TITLE
StandaloneFileBrowser.cs:16~22

### ISSUE THREAD

**Issue by Calvin2274** [gkngkc/UnityStandaloneFileBrowser#12]
Need change as below or have exception if run on editor.

`#if UNITY_EDITOR`
`_platformWrapper = new StandaloneFileBrowserEditor();`
`#elif UNITY_STANDALONE_OSX`
`_platformWrapper = new StandaloneFileBrowserMac();`
`#elif UNITY_STANDALONE_WIN`
`_platformWrapper = new StandaloneFileBrowserWindows();`
`#endif`

**Comment by gkngkc** [comment]
Your build settings / target platform should be mac os x when your are on a mac. Windows platform plugins doesn't work on mac. Maybe you can improve platform wrapper selection with compiler flags like UNITY_EDITOR_WIN, UNITY_EDITOR_OSX.
