### ISSUE TITLE
ArgumentException of System.Windows.Forms.dll

### ISSUE THREAD

**Issue by Calvin2274** [gkngkc/UnityStandaloneFileBrowser#13]
Issue found when Making Window Standalone Build using Mac
OSX : 10.11.6
Unity : 5.6.1p1

ArgumentException: The Assembly System.Drawing is referenced by System.Windows.Forms ('Assets/StandaloneFileBrowser/Plugins/System.Windows.Forms.dll'). But the dll is not allowed to be included or could not be found.

**Comment by gkngkc** [comment]
Be sure api compatibility level is .NET 2.0, not the subset.
