### ISSUE TITLE
The type or namespace name `Windows' does not exist in the namespace `System

### ISSUE THREAD

**Issue by jBachalo** [gkngkc/UnityStandaloneFileBrowser#14]
Get the following 3 errors, whether I open using Unity in Windows or on the Mac the moment I target Windows in Build Settings.

Assets/StandaloneFileBrowser/StandaloneFileBrowserWindows.cs(5,14): error CS0234: The type or namespace name `Windows' does not exist in the namespace `System'. Are you missing an assembly reference?

Assets/StandaloneFileBrowser/StandaloneFileBrowserWindows.cs(7,7): error CS0246: The type or namespace name `Ookii' could not be found. Are you missing an assembly reference?

Assets/StandaloneFileBrowser/StandaloneFileBrowserWindows.cs(15,34): error CS0246: The type or namespace name `IWin32Window' could not be found. Are you missing an assembly reference?

**Comment by gkngkc** [comment]
Probably dll import platform checks are wrong. Be sure Ookii.Dialogs.dll and System.Windows.Forms.dll platform dependencies are correct, Editor & Standalone ( Windows ) [settings](https://forum.unity3d.com/attachments/sfb-jpeg.230164/) should checked

**Comment by jBachalo** [comment]
Thanks..seems to be it . Also, as mentioned elsewhere, need to remember to not use .Net subset
