### ISSUE TITLE
Mac image preview only shows spinner

### ISSUE THREAD

**Issue by pmaloka** [gkngkc/UnityStandaloneFileBrowser#19]
When selecting image files, with the view set to the 3rd view type (that shows an image preview in the rightmost panel), the image never loads and is instead, just the spinner.
![opendialog](https://user-images.githubusercontent.com/320530/31586941-8d7df6d0-b1a6-11e7-97e1-7e9bb8465577.jpg)

**Comment by gkngkc** [comment]
Hi,

Thanks for reporting, should be fixed with 636db994a57b51ccb48e699b21086bd700ea1faf

**Comment by pmaloka** [comment]
Sweet! Thanks so much!

Can confirm it now works.
