### ISSUE TITLE
Window Title text looks weird on Mac

### ISSUE THREAD

**Issue by foxnoodles** [gkngkc/UnityStandaloneFileBrowser#20]
Would Be nice to have it vertically centered and also the title container is too big(in height)... Kinda lost it's native look and feel.

**Comment by gkngkc** [comment]
Unfortunately i can't do much about it, because that's the osx's default. Apple [removed ](https://stackoverflow.com/questions/36879212/title-bar-missing-in-nsopenpanel)"title" field and i have to set "message" field to display a text.

**Comment by foxnoodles** [comment]
damn :/
