### ISSUE TITLE
Opening file browser broken on mac, missing dll

### ISSUE THREAD

**Issue by GafferSystems** [gkngkc/UnityStandaloneFileBrowser#24]
Unity 2017.1.1f1
1. Started new Unity3d project.
2. Switched build settings to Mac OS X x86.
3. Imported by doubleclicking StandaloneFileBrowser.unitypackage from readme.
4. Opened CanvasSampleScene.
5. Clicked "Open File - Image".

Got: DllNotFoundException: StandaloneFileBrowser
![error log](https://user-images.githubusercontent.com/32983453/33715874-5c98322e-db54-11e7-81d0-7508944296d9.png)

**Comment by GafferSystems** [comment]
@gkngkc Any news on this? Seems to be broken for mac on newer versions of Unity all together.

**Comment by gkngkc** [comment]
Hi,

If i understand correctly, you're running editor with mac build settings on a windows machine. If this is the case, it won't work because of the plugin selection [code](https://github.com/gkngkc/UnityStandaloneFileBrowser/blob/master/Assets/StandaloneFileBrowser/StandaloneFileBrowser.cs#L17).  You can use EDITOR compile flags to select correct plugin.

**Comment by GafferSystems** [comment]
Hi again!
We have now ran it on a Mac, standalone outside the editor, and it's still not working, we get a different error message here though.
![screen shot 2017-12-14 at 21 02 32](https://user-images.githubusercontent.com/32983453/34012030-7b091fb6-e112-11e7-925d-1f8d5e196d22.png)

**Comment by gkngkc** [comment]
It's probably because of WWW.  You can check these two things,
- Is path[0]'s value correct? 
- Is it works with File.LoadAllBytes?

**Comment by GafferSystems** [comment]
@gkngkc 
I tried once again on windows and mac.
On Windows it works perfectly, and the path[0] returns: "C:\Users\Myname\Desktop\image.png

On mac it crashes with the UriFormatException, and path[0] returns:
file:///Users/Myname/Desktop/image.png

**Comment by GafferSystems** [comment]
Seems like adding file:// to the www was the issue, seems like it works for windows but not mac if its' added. Removing it from the line, so it becomes `WWW www = new WWW (paths[0]);` Fixes everything. Thanks for your time @gkngkc and hope this can help others encountering the same issue.
