### ISSUE TITLE
UnityPackage scene is empty

### ISSUE THREAD

**Issue by Naphier** [gkngkc/UnityStandaloneFileBrowser#3]
First off, excellent work. So far I've yet to encounter an issue. I'm setting it up for UnityEvent callbacks so, if I ever have time I'll contribute that work back to you.
When I imported the unity package from
https://github.com/gkngkc/UnityStandaloneFileBrowser/tree/master/Package
The example scene was completely empty. No biggy though because I imagine the sample scene was just a camera with your sample script attatched.
Anyway, all works out of the box other than that (so far).
Thanks for the contribution!!

**Comment by gkngkc** [comment]
Thank you very much for kind words.

Like you said, sample scene is just camera + script and honestly, i didn't test it much. Maybe i did something wrong while exporting package, i'll check it out, thanks for pointing that out.

I did consider implement an async version but it wasn't a necessary for me at the time, so i didn't do it. But if you do it i'll happily merge it.
