### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [gkngkc/UnityStandaloneFileBrowser#30]
Is it possible to have Linux support using GTK?

**Comment by gkngkc** [comment]
It's possible but i never tried actually. There are c implementations out there like [this](https://github.com/mlabbe/nativefiledialog/blob/master/src/nfd_gtk.c), but i think it can be done with gtk-sharp without using native code bindings.

**Comment by RicardoEPRodrigues** [comment]
If I have time I'll mess around with GTK# and Unity.

**Comment by RicardoEPRodrigues** [comment]
Linux is implemented since https://github.com/gkngkc/UnityStandaloneFileBrowser/pull/41
