### ISSUE TITLE
Open Filebrowser doesn't respect directory parameter (Win10-64bit)

### ISSUE THREAD

**Issue by Naphier** [gkngkc/UnityStandaloneFileBrowser#4]
Not sure if this problem is exhibited in other Windows versions, but the directory parameter does nothing. The browser always opens to the last location. Probably an issue with Ookii.
Would be nice to get this to work, but if it's an issue with Ookii then it'd be difficult without re-writing that portion of Ookii or writing your own library to handle this.

**Comment by gkngkc** [comment]
Looks like an Ookii bug. As a workaround i've sent directory as FileName, this should do the work.

Commit 6f29d000225102f83d533787e37419eb6e388842

**Comment by Naphier** [comment]
Seems to work perfectly. Thanks for that quick turnaround!

**Comment by gkngkc** [comment]
You're welcome. 

Also i forgot SaveFileDialog. Applied same fix for it.

Commit: f15b57a78ca49d92a43485cce73b6b9458ebba38
