### ISSUE TITLE
Filename containing commas is split into multiple entries

### ISSUE THREAD

**Issue by dbouianov** [gkngkc/UnityStandaloneFileBrowser#5]
Here's an example of a valid filename we work with:

"Final total approved set Nov 28,2016 14012_INTERLEAF_Approved_Plans_6546176-6473974-page5.pdf"

Comma is a valid character in an actual filename, but it's used to separate filename entries from each other inside the Mac plugin, regardless of whether multi-select flag is set to true.

The plugin needs to avoid separating filename entries with any character that can be present in the filename itself. One way to fix this is for the plugin to return an array instead of a string consisting of filenames with a separator character in between.

**Comment by gkngkc** [comment]
Oops i didn't think that :)

I think returning array from obj-c is unnecessary complexity for this task so i changed separator character to ascii control character 28.

Thanks for pointing it out.

**Comment by dbouianov** [comment]
Works like a charm, thank you!
