### ISSUE TITLE
[Not the usual?] ArgumentException: System.Windows.Forms.dll in Mac

### ISSUE THREAD

**Issue by giggioz** [gkngkc/UnityStandaloneFileBrowser#56]
Hi,

I tried to find a similar issue among the others but I think this is a different case.

I'm using a Mac Book Pro with Unity 2018.3.4.f1 and I want to build a Windows Standalone App.

Using this plugin gives me this error at building time:

```
ArgumentException: The Assembly Mono.WebBrowser is referenced by System.Windows.Forms ('Assets/Plugins/StandaloneFileBrowser/Plugins/System.Windows.Forms.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:150)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:156)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:190)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

The file is in the correct path and here my settings

![image](https://user-images.githubusercontent.com/6266740/54388768-c2e3d900-469e-11e9-87c5-b4fd758bae64.png)

![image](https://user-images.githubusercontent.com/6266740/54388779-cc6d4100-469e-11e9-82d7-a9d90456bf8a.png)

If someone needs other information just ask, thanks!

**Comment by giggioz** [comment]
I changed these settings


![image](https://user-images.githubusercontent.com/6266740/54390229-47842680-46a2-11e9-92a2-0d1376961ca6.png)

And it worked!

**Comment by UnVoiding** [comment]
Thanks, @giggioz! It worked for me too. Do you know the real cause of the issue? Changing compatibility level to 4.0 looks like an overkill and can harm other dependencies

**Comment by giggioz** [comment]
I'm sorry, I did not investigate the cause :/
