### ISSUE TITLE
ArgumentException: The Assembly System.Drawing is referenced by System.Windows.Forms

### ISSUE THREAD

**Issue by grzegorzbojar** [gkngkc/UnityStandaloneFileBrowser#6]
Does this file browser work only in Unity or it should work also after build? Unfortunately I am getting an error:

> ArgumentException: The Assembly System.Drawing is referenced by System.Windows.Forms ('Assets/StandaloneFileBrowser/Plugins/System.Windows.Forms.dll'). But the dll is not allowed to be included or could not be found.
> UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:146)
> UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:152)
> UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:184)

**Comment by gkngkc** [comment]
It should work in the build. Be sure Player Settings / Api Compatibility Level is .NET 2.0.

**Comment by Knightsurfer** [comment]
you need to import the System.Drawing and maybe also System.Deployment
