### ISSUE TITLE
Only works in editor?

### ISSUE THREAD

**Issue by filipbahnan** [gkngkc/UnityStandaloneFileBrowser#68]
I can open the file explorer easily in the editor but when I build the game nothing happens when I try to open the file explorer.  I am using .NET 4.x and Im using steam VR.

Does anyone know what is going on?

(I am not trying to show the file explorer through the VR, I want it to show up on my normal monitor which it does in the editor but it does not work in built version)

**Comment by AliMatias** [comment]
I don't know if it helps, but i had some errors popup when building the standalone app.
But i changed the API level from 2.0 to 4.0 and it built just fine. And it works wonderfuly.
The guide says you have to select 2.0 though. So there's that
