### ISSUE TITLE
Unhandled exception: Unity 5.3.4

### ISSUE THREAD

**Issue by rorywalsh** [gkngkc/UnityStandaloneFileBrowser#7]
First off, thanks for sharing this. It looks great. Only thing is I get an unhandled exception when I try to import this package into my scene. Any ideas? Here's what Unity is telling me:

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 

The following assembly referenced from /Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/Ookii.Dialogs.dll could not be loaded:
     Assembly:   System.Drawing    (assemblyref_index=4)
     Version:    2.0.0.0
     Public Key: b03f5f7f11d50a3a
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/).

Could not load file or assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The following assembly referenced from /Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/System.Windows.Forms.dll could not be loaded:
     Assembly:   System.Drawing    (assemblyref_index=1)
     Version:    2.0.0.0
     Public Key: b03f5f7f11d50a3a
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/).

Could not load file or assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Could not load file or assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The class System.Windows.Forms.Control could not be loaded, used in System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Could not load file or assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The class Ookii.Dialogs.ExtendedForm could not be loaded, used in Ookii.Dialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0c15020868fd6249
The class System.Windows.Forms.Form could not be loaded, used in System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class Ookii.Dialogs.VistaFileDialog could not be loaded, used in Ookii.Dialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0c15020868fd6249
Could not load file or assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The class Ookii.Dialogs.TaskDialog could not be loaded, used in Ookii.Dialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0c15020868fd6249
The following assembly referenced from /Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/Ookii.Dialogs.dll could not be loaded:
     Assembly:   System.Design    (assemblyref_index=3)
     Version:    2.0.0.0
     Public Key: b03f5f7f11d50a3a
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/Users/walshr/sourcecode/UnityProject/Assets/StandaloneFileBrowser/Plugins/).

Could not load file or assembly 'System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by gkngkc** [comment]
Thank you for kind words. 

Windows plugin platform checks was wrong, my bad. Can you try importing new package?

**Comment by rorywalsh** [comment]
Brilliant. That fixed it. Thanks for the quick response.
