### ISSUE TITLE
Mac version causes Unity to freeze when opening files with any extension filter on it

### ISSUE THREAD

**Issue by cchengVA** [gkngkc/UnityStandaloneFileBrowser#8]
Unless an empty extension filter string is passed to the call to [DialogOpenFilePanel](https://github.com/gkngkc/UnityStandaloneFileBrowser/blob/master/Assets/StandaloneFileBrowser/StandaloneFileBrowserMac.cs#L9), that call will immediately lock up Unity with zero means to recover it.  No open dialog pops up, and neither does any error messages.

I'm not a good enough Mac developer to be able to root through the exact causes, however I feel the cause lies somewhere in the Plugin you provide, rather than anywhere in Unity's space.

**Comment by cchengVA** [comment]
Almost forgot; using Unity 5.5.0f3.

**Comment by cchengVA** [comment]
...my apologies, my inexperience with Mac led me to believe there were no logs.  I just found them.

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSOpenPanel setAccessoryViewDisclosed:]: unrecognized selector sent to instance 0x105327b90
*** First throw call stack:
0  CoreFoundation         __exceptionPreprocess + 172
1  lobobjc.A.dylib        objc_exception_throw + 43
2  CoreFoundation         -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3  CoreFoundation         ___forwarding___ + 1010
4  CoreFoundation         _CF_forwarding_prep_0 + 120
5  StandaloneFileBrowser  -[StandaloneFileBrowser dialogOpenFilePanel:director:filters:multiselect:canChooseFiles:canChooseFolders:] + 746
6  StandaloneFileBrowser  DialogOpenFilePanel + 178`
...all the way to the start of the application.

**Comment by gkngkc** [comment]
Hi,

You're right, i just tested it and calling open file method like

`var extensions = new [] {
                new ExtensionFilter("All Files")
            };
            StandaloneFileBrowser.OpenFilePanel("Open File", "", extensions, true);`

causes a objective-c exception and its crashes editor/app.

I'm going to add a safe parse check or an exception handler to prevent this whenever i have free time.

Thank you for your feedback

**Comment by cchengVA** [comment]
I should probably mention, that even with the sample you provided, unmodified, it was still locking up Unity when trying to create an open file dialog with any filter...

**Comment by erikpg** [comment]
I'm seeing the same issue here.

**Comment by gkngkc** [comment]
This should be fixed with https://github.com/gkngkc/UnityStandaloneFileBrowser/commit/168cacb2e9afeb68bc00f97c21ddd467ee723a5e.

Sorry for the late fix, it was an issue with a [method](https://github.com/gkngkc/UnityStandaloneFileBrowser/blob/master/Plugins/MacOS/StandaloneFileBrowser/Plugin.mm#L79) unavailable mac os < 10.11.

**Comment by erikpg** [comment]
Awesome!!  It is working great now.  Thanks a lot 👍
