### ISSUE TITLE
Windows Namespace missing

### ISSUE THREAD

**Issue by arulbabu** [gkngkc/UnityStandaloneFileBrowser#9]
Sorry it may be simple error. i am getting "The type or namespace name `Windows' does not exist in the namespace `System'. Are you missing an assembly reference?"

can any one help me in this. 
Thanks

**Comment by gkngkc** [comment]
Hi,

Can you try new package i just commit. Windows dll's platform checks was wrong in the old package.

If this not solves your issue, be sure "Plugins/Ookii.Dialogs.dll" and "Plugins/System.Windows.Forms.dll" platform checks are correct and PlayerSettings/Api Compatibility level is .NET 2.0
