### ISSUE TITLE
Can't build in 2020.1.1f1

### ISSUE THREAD

**Issue by windBugg** [gkngkc/UnityStandaloneFileBrowser#93]
About a week ago I was able to build the project fine however now every time I try I get the following error:

ArgumentException: The Assembly Mono.WebBrowser is referenced by System.Windows.Forms ('Assets/StandaloneFileBrowser/Plugins/System.Windows.Forms.dll'). But the dll is not allowed to be included or could not be found.

It functions properly in the editor but does this when attempting to create a build.

![image](https://user-images.githubusercontent.com/54188782/93685823-ef409880-fa7f-11ea-8ac2-06e5a7f4495f.png)

**Comment by Sexagom** [comment]
This is already fix:
https://github.com/gkngkc/UnityStandaloneFileBrowser/issues/87
